version: "3.8"

services:
  booklovers:
    build: ""
    command: python manage.py runserver_plus 0.0.0.0:8000 --cert-file cert.crt
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8888:8000
    env_file:
      - .env
    depends_on:
      - booklovers_db

  booklovers_db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    env_file:
      - .env
    ports:
      - "5434:5432"

volumes:
  postgres_data:
